GET https://localhost:7166/products

###

GET https://localhost:7166/categories

###

GET https://localhost:7166/users/11

###

GET https://localhost:7166/users

###

POST https://localhost:7166/login
content-type: application/json

{
  "login": "newUser",
  "password": "123456",
  "email": "newU12ser11@gmail.com"
}

###

POST https://localhost:7166/register
content-type: application/json

{
  "login": "newUser",
  "password": "123456",
  "email": "122346"
}

###


DELETE https://localhost:7166/users/delete/117


###

POST https://localhost:7166/users
content-type: application/json

{
  "login": "newUser",
  "password": "123456",
  "email": "754.com"
}

###

POST https://localhost:7166/products
content-type: application/json

{
  "title": "product",
  "categoriesId": "6",
  "image": "1424"
}

###

DELETE https://localhost:7166/products/88

###